version: "3.7"
services:
  backend:
    image: laudspeaker:api-latest
    network_mode: "host"
    depends_on:
      - redis
      - postgres
      - mongo
      - clickhouse
  
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laudspeaker
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: on-failure
    ports:
      - "8123:8123"
      - "9000:9000"

networks:
  default:
    name: laudspeaker_default
