version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
  
  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: laudspeaker
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"