version: "3.7"
services:
  backend:
    image: laudspeaker:api-latest
    network_mode: "host"
    depends_on:
      - redis
      - postgres
      - mongo
      - clickhouse
  
  redis:
    image: redis:alpine
    command: redis-server
    network_mode: "host"
    environment:
      - REDIS_REPLICATION_MODE=master

  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laudspeaker
    network_mode: "host"
    restart: unless-stopped

  mongo:
    image: "mongo:latest"
    network_mode: "host"


  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: on-failure
    network_mode: "host"


networks:
  default:
    name: laudspeaker_default
