version: "3.7"
services:
  e2e-electron:
    image: cypress/included:10.3.1-typescript
    image: "cypress/included:10.8.0"
    working_dir: /
    command: "--browser chrome"
    volumes:
      - ./packages/client/cypress.config.ts:/cypress.config.ts
      - ./packages/client/cypress:/cypress
    environment:
      - BASE_URL=http://frontend:3000
networks:
  default:
    name: laudspeaker_default
    external: true
