services:
  - type: web
    name: laudspeaker
    healthCheckPath: /
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: PORT
        value: 80
