services:
  - type: web
    name: laudspeaker
    healthCheckPath: /
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: PORT
        value: 80
  - type: redis
    name: laudspeaker
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
  - type: pserv
      name: clickhouse
      env: docker
      disk:
        name: data
        mountPath: /var/lib/clickhouse
        sizeGB: 10
  - type: pserv
    name: mongodb
    env: docker
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
databases:
- name: laudspeaker-db
  databaseName: laudspeaker
